### ISSUE TITLE
Hello, can you provide the dataset? 

### ISSUE THREAD

**Issue by FrankMMMMMM** [nguyenquivinhquang/Multi-camera-People-Tracking-With-Mixture-of-Realistic-and-Synthetic-Knowledge#2]
@nguyenquivinhquang 
Hello, can you provide the dataset?

**Comment by zef1611** [comment]
Hi, you can request to access the dataset with the following link: https://www.aicitychallenge.org/2023-data-and-evaluation/

**Comment by NQHuy1905** [comment]
@zef1611 @nguyenquivinhquang Hi, current official link is now not accessible, can you share the link to dataset
