### ISSUE TITLE
datasets/reid

### ISSUE THREAD

**Issue by zzifer** [nguyenquivinhquang/Multi-camera-People-Tracking-With-Mixture-of-Realistic-and-Synthetic-Knowledge#4]
Thank you for your contribution. Can you tell me how the files under your datasets/reid are generated?

**Comment by nguyenquivinhquang** [comment]
Hi Feng,

These files I randomly generated from the dataset and only used to validate
my ReID model

Best regards,
Quang

**Comment by zzifer** [comment]
Thanks for your reply, I understand
