### ISSUE TITLE
the link is dead

### ISSUE THREAD

**Issue by yizhanchengshou** [nguyenquivinhquang/Multi-camera-People-Tracking-With-Mixture-of-Realistic-and-Synthetic-Knowledge#6]
The link has expired and the trained model and dataset cannot be downloaded. Can you upload another copy?

**Comment by joaorulff** [comment]
I have the same issue. Would you have another link?

**Comment by nguyenquivinhquang** [comment]
I updated the new link for reid checkpoint and dataset for training in here
https://drive.google.com/drive/folders/1_STPMade1hWAbxvpAvFX0LevKMh1z_ND
